<a href="https://colab.research.google.com/github/dmhenaopa/EDCO/blob/main/Proyectos/Proyecto_COVID.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 1. Obtener y concatenar los datos

In [1]:
from google.colab import drive
drive.mount('/content/drive',force_remount=True)

Mounted at /content/drive

In [3]:
# Librerias y sistema operativo
import os

import glob
import pandas as pd
import numpy as np

In [4]:
# Movernos a la carpeta base con los archivos/subcarpetas
ruta = '/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2/BaseDatos'
os.chdir(ruta)
!ls # Listar contenido

Proceso_1   Proceso_4  Proceso_8	  Proceso_Header_2  Proceso_Header_6
Proceso_10  Proceso_5  Proceso_9	  Proceso_Header_3  Proceso_Header_7
Proceso_2   Proceso_6  Proceso_Header_1   Proceso_Header_4  Proceso_Header_8
Proceso_3   Proceso_7  Proceso_Header_10  Proceso_Header_5  Proceso_Header_9

In [5]:
# Concatenar los 10 archivos en uno solo
lista_archivos = []

for i in range(1, 11):
  ruta_carpeta = ('Proceso_Header_{}/*.csv'.format(i)) # Ruta carpeta por carpeta
  archivos_carpeta = glob.glob(ruta_carpeta) # Buscar los archivos con patron especifico
  lista_archivos.extend(archivos_carpeta)

df_concat = pd.concat(
    [pd.read_csv(f) for f in lista_archivos], ignore_index=True
)

ruta_proyecto = '/content/drive/MyDrive/EDCO_IntroCienciaDatos/Proyectos'
os.chdir(ruta_proyecto)
df_concat.to_csv('archivo_concatenado.csv', index=False, header=True)

# 2. Limpieza de los datos

In [6]:
# Verificar datos del archivo csv
df_concat.head(5) # Visualizar dataframe

,fecha reporte web,ID de caso,Fecha de notificación,Código DIVIPOLA departamento,Nombre departamento,Código DIVIPOLA municipio,Nombre municipio,Edad,Unidad de medida de edad,Sexo,...,Código ISO del país,Nombre del país,Recuperado,Fecha de inicio de síntomas,Fecha de muerte,Fecha de diagnóstico,Fecha de recuperación,Tipo de recuperación,Pertenencia étnica,Nombre del grupo étnico
0,2022-01-12 00:00:00,"5,399,804",2022-01-10 00:00:00,5,ANTIOQUIA,"5,001",MEDELLIN,45,1,F,...,NaN,NaN,Recuperado,2022-01-06 00:00:00,NaN,2022-01-10 00:00:00,2022-01-20 00:00:00,Tiempo,6.0,NaN
1,2022-01-16 00:00:00,"5,520,445",2022-01-02 00:00:00,73,TOLIMA,"73,001",IBAGUE,44,1,F,...,NaN,NaN,Recuperado,2021-12-30 00:00:00,NaN,2022-01-13 00:00:00,2022-01-17 00:00:00,Tiempo,6.0,NaN
2,2021-12-30 00:00:00,"5,141,954",2021-12-27 00:00:00,11,BOGOTA,"11,001",BOGOTA,30,1,F,...,NaN,NaN,Recuperado,2021-12-27 00:00:00,NaN,2021-12-28 00:00:00,2022-01-10 00:00:00,Tiempo,6.0,NaN
3,2021-06-10 00:00:00,"3,642,260",2021-06-08 00:00:00,85,CASANARE,"85,001",YOPAL,71,1,M,...,NaN,NaN,Recuperado,2021-05-24 00:00:00,NaN,2021-06-08 00:00:00,2021-06-11 00:00:00,Tiempo,6.0,NaN
4,2020-12-24 00:00:00,"1,551,989",2020-12-22 00:00:00,11,BOGOTA,"11,001",BOGOTA,48,1,F,...,NaN,NaN,Recuperado,2020-12-12 00:00:00,NaN,2020-12-22 00:00:00,2021-01-06 00:00:00,Tiempo,6.0,NaN

In [7]:
df_concat.shape # Dimensión de la matriz

(3000, 23)

In [8]:
df_concat.info() # Consultar info de DB, cuales son categóricas y númericas

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 23 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   fecha reporte web             3000 non-null   object
 1   ID de caso                    3000 non-null   object
 2   Fecha de notificación         3000 non-null   object
 3   Código DIVIPOLA departamento  3000 non-null   object
 4   Nombre departamento           3000 non-null   object
 5   Código DIVIPOLA municipio     3000 non-null   object
 6   Nombre municipio              3000 non-null   object
 7   Edad                          3000 non-null   int64
 8   Unidad de medida de edad      3000 non-null   int64
 9   Sexo                          3000 non-null   object
 10  Tipo de contagio              3000 non-null   object
 11  Ubicación del caso            2978 non-null   object
 12  Estado                        2978 non-null   object
 13  Código ISO del país           2 non-null      object
 14  Nombre del país               2 non-null      object
 15  Recuperado                    2980 non-null   object
 16  Fecha de inicio de síntomas   2748 non-null   object
 17  Fecha de muerte               83 non-null     object
 18  Fecha de diagnóstico          2999 non-null   object
 19  Fecha de recuperación         2918 non-null   object
 20  Tipo de recuperación          2918 non-null   object
 21  Pertenencia étnica            2999 non-null   float64
 22  Nombre del grupo étnico       32 non-null     object
dtypes: float64(1), int64(2), object(20)
memory usage: 539.2+ KB

In [9]:
# Columnas irrelevantes para nuestro analisis

# 1. Columna que no contiene información relevante para el problema que queremos resolver
# 2. Columna categorica pero con un solo nivel - No nos da información adicional
# 3. Columna númerica pero con un solo valor

# Para columnas categoricas - Cuantos niveles tenemos en cada columna
columnas_cat = [
    'fecha reporte web',
    'ID de caso',
    'Fecha de notificación',
    'Código DIVIPOLA departamento',
    'Nombre departamento',
    'Código DIVIPOLA municipio',
    'Nombre municipio',
    'Sexo',
    'Tipo de contagio',
    'Ubicación del caso',
    'Estado',
    'Código ISO del país',
    'Nombre del país',
    'Recuperado',
    'Fecha de inicio de síntomas',
    'Fecha de muerte',
    'Fecha de diagnóstico',
    'Fecha de recuperación',
    'Tipo de recuperación',
    'Nombre del grupo étnico'
]

for col in columnas_cat:
  print(f'Columna ´´{col}´´: {df_concat[col].nunique()} subniveles')
#

Columna ´´fecha reporte web´´: 604 subniveles
Columna ´´ID de caso´´: 3000 subniveles
Columna ´´Fecha de notificación´´: 656 subniveles
Columna ´´Código DIVIPOLA departamento´´: 35 subniveles
Columna ´´Nombre departamento´´: 35 subniveles
Columna ´´Código DIVIPOLA municipio´´: 326 subniveles
Columna ´´Nombre municipio´´: 320 subniveles
Columna ´´Sexo´´: 2 subniveles
Columna ´´Tipo de contagio´´: 3 subniveles
Columna ´´Ubicación del caso´´: 3 subniveles
Columna ´´Estado´´: 3 subniveles
Columna ´´Código ISO del país´´: 2 subniveles
Columna ´´Nombre del país´´: 2 subniveles
Columna ´´Recuperado´´: 3 subniveles
Columna ´´Fecha de inicio de síntomas´´: 651 subniveles
Columna ´´Fecha de muerte´´: 76 subniveles
Columna ´´Fecha de diagnóstico´´: 649 subniveles
Columna ´´Fecha de recuperación´´: 577 subniveles
Columna ´´Tipo de recuperación´´: 2 subniveles
Columna ´´Nombre del grupo étnico´´: 15 subniveles

In [10]:
# Para columnas númericas - Niveles diferentes
df_concat.describe() # Std es 0 en la columna los valores son exacta/ iguales

              Edad  Unidad de medida de edad  Pertenencia étnica
count  3000.000000               3000.000000         2999.000000
mean     40.196000                  1.005333            5.922307
std      18.695581                  0.072847            0.534000
min       1.000000                  1.000000            1.000000
25%      27.000000                  1.000000            6.000000
50%      38.000000                  1.000000            6.000000
75%      53.000000                  1.000000            6.000000
max     101.000000                  2.000000            6.000000

In [11]:
# Codigo ISO del país y Nombre del país tiene muy
# pocos registros no nulos y no parecen relevantes. Se pueden ignorar esas columnas
df_concat.drop(
    columns=[
        'Código ISO del país',
        'Nombre del país'
        ],
    inplace=True
)
df_concat.info() # Eliminar las dos columnas y verificar

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 21 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   fecha reporte web             3000 non-null   object
 1   ID de caso                    3000 non-null   object
 2   Fecha de notificación         3000 non-null   object
 3   Código DIVIPOLA departamento  3000 non-null   object
 4   Nombre departamento           3000 non-null   object
 5   Código DIVIPOLA municipio     3000 non-null   object
 6   Nombre municipio              3000 non-null   object
 7   Edad                          3000 non-null   int64
 8   Unidad de medida de edad      3000 non-null   int64
 9   Sexo                          3000 non-null   object
 10  Tipo de contagio              3000 non-null   object
 11  Ubicación del caso            2978 non-null   object
 12  Estado                        2978 non-null   object
 13  Recuperado                    2980 non-null   object
 14  Fecha de inicio de síntomas   2748 non-null   object
 15  Fecha de muerte               83 non-null     object
 16  Fecha de diagnóstico          2999 non-null   object
 17  Fecha de recuperación         2918 non-null   object
 18  Tipo de recuperación          2918 non-null   object
 19  Pertenencia étnica            2999 non-null   float64
 20  Nombre del grupo étnico       32 non-null     object
dtypes: float64(1), int64(2), object(18)
memory usage: 492.3+ KB

In [12]:
# Duplicados - Verificar filas repetidas
# Eliminar Datos - Fila completa si hubiese duplicados
# df_concat.dropna(inplace=True) # Inplace=True sobreescriba el dropna en el dataset
filas_duplicadas = df_concat[df_concat.duplicated()]
filas_duplicadas.shape

(0, 21)

In [19]:

# Problema con los datos, paciente real que tiene ambas fechas 'muerte y recuperación'
## Fecha de recuperación y tipo (82 nulos) -> verificar Probablemente coinciden con las personas que fallecieron (83 casos)
#  Verificar si esos nulos corresponden a los fallecidos. Si es así, puedes rellenar Tipo de recuperación con 'No aplica (Fallecido)'

# Creamos columnas temporales que indiquen True si es nulo y False si no lo es
fallecido = df_concat['Fecha de muerte'].isna() # False cuando NO esta vacio
sin_recuperacion = df_concat['Fecha de recuperación'].isna() # False cuando NO esta vacio

# Generamos una tabla cruzada - No tienen fecha de recup, personas que fallecieron
print(pd.crosstab(fallecido, sin_recuperacion, rownames=['Muerte es Nula'], colnames=['Recuperación es Nula']))

# Encontrar al paciente que tiene AMBAS fechas registradas
paciente_error = df_concat[df_concat['Fecha de muerte'].notna() & df_concat['Fecha de recuperación'].notna()]
print(paciente_error[['ID de caso', 'Fecha de muerte', 'Fecha de recuperación', 'Estado']])


###################
paciente_error = df_concat[df_concat['Fecha de muerte'].notna() & df_concat['Fecha de recuperación'].notna()]

print("El paciente con la anomalía real es:")
print(paciente_error[['ID de caso', 'Fecha de muerte', 'Fecha de recuperación', 'Estado']]) # Hay dos pacientes asi

# Ver la columna 'Recuperado' para desempatar
print("Ver columna Recuperado:")
print(df_concat.loc[[1815, 1852], ['ID de caso', 'Fecha de muerte', 'Fecha de recuperación', 'Recuperado']]) # Fecha de muerte son errores

#-------------------------------------------
# Borrar fecha de muerte que está errada y asignar Estado = 'Leve'
indices_anomalia = [1815, 1852] # Índices de los pacientes con la anomalía

df_concat.loc[indices_anomalia, 'Fecha de muerte'] = np.nan # Borrar la fecha de muerte falsa poniéndole NaN

df_concat.loc[indices_anomalia, 'Estado'] = 'Leve' # Corregir su Estado a 'Leve' (en lugar del NaN que tenían)

# Verificar
print("Registros corregidos exitosamente:")
print(df_concat.loc[indices_anomalia, ['ID de caso', 'Fecha de muerte', 'Fecha de recuperación', 'Estado']])

Recuperación es Nula  False  True
Muerte es Nula
False                  2918     82
     ID de caso Fecha de muerte Fecha de recuperación Estado
0     5,399,804       No aplica   2022-01-20 00:00:00   Leve
1     5,520,445       No aplica   2022-01-17 00:00:00   Leve
2     5,141,954       No aplica   2022-01-10 00:00:00   Leve
3     3,642,260       No aplica   2021-06-11 00:00:00   Leve
4     1,551,989       No aplica   2021-01-06 00:00:00   Leve
...         ...             ...                   ...    ...
2995     92,138       No aplica   2020-07-21 00:00:00   Leve
2996  2,843,768       No aplica   2021-05-10 00:00:00   Leve
2997    364,258       No aplica   2020-08-22 00:00:00   Leve
2998  3,823,676       No aplica   2021-06-19 00:00:00   Leve
2999  1,084,295       No aplica   2020-11-06 00:00:00   Leve

[2918 rows x 4 columns]
El paciente con la anomalía real es:
     ID de caso Fecha de muerte Fecha de recuperación Estado
0     5,399,804       No aplica   2022-01-20 00:00:00   Leve
1     5,520,445       No aplica   2022-01-17 00:00:00   Leve
2     5,141,954       No aplica   2022-01-10 00:00:00   Leve
3     3,642,260       No aplica   2021-06-11 00:00:00   Leve
4     1,551,989       No aplica   2021-01-06 00:00:00   Leve
...         ...             ...                   ...    ...
2995     92,138       No aplica   2020-07-21 00:00:00   Leve
2996  2,843,768       No aplica   2021-05-10 00:00:00   Leve
2997    364,258       No aplica   2020-08-22 00:00:00   Leve
2998  3,823,676       No aplica   2021-06-19 00:00:00   Leve
2999  1,084,295       No aplica   2020-11-06 00:00:00   Leve

[2918 rows x 4 columns]
Ver columna Recuperado:
     ID de caso Fecha de muerte Fecha de recuperación  Recuperado
1815  3,380,782       No aplica   2021-06-09 00:00:00  Recuperado
1852  1,649,247       No aplica   2021-01-13 00:00:00  Recuperado
Registros corregidos exitosamente:
     ID de caso Fecha de muerte Fecha de recuperación Estado
1815  3,380,782             NaN   2021-06-09 00:00:00   Leve
1852  1,649,247             NaN   2021-01-13 00:00:00   Leve

In [22]:
# Valores nulos/faltantes - Eliminar, imputo, dejarlos en el documento
## Fecha de muerte (Solo 83 no-nulos de 3000): Significa que el paciente sobrevivió
df_concat['Fecha de muerte'] = df_concat['Fecha de muerte'].fillna('No aplica')

## Nombre del grupo étnico (Solo 32 no-nulos): No pertenece a un grupo étnico específico
df_concat['Nombre del grupo étnico'] = df_concat['Nombre del grupo étnico'].fillna('No aplica')

## Fecha de inicio de síntomas: Rellenar con la 'Fecha de diagnóstico' quizás asintomaticos
df_concat['Fecha de inicio de síntomas'] = df_concat[
    'Fecha de inicio de síntomas'
    ].fillna(df_concat['Fecha de diagnóstico'])

###################

## Estado y condición del paciente: Para no sesgar análisis, se convierten en nueva categoría "Desconocido"
df_concat['Estado'] = df_concat['Estado'].fillna('Desconocido')
df_concat['Ubicación del caso'] = df_concat['Ubicación del caso'].fillna('Desconocido')

###################

# Revisar el estado de la tabla actualmente
df_concat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 21 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   fecha reporte web             3000 non-null   object
 1   ID de caso                    3000 non-null   object
 2   Fecha de notificación         3000 non-null   object
 3   Código DIVIPOLA departamento  3000 non-null   object
 4   Nombre departamento           3000 non-null   object
 5   Código DIVIPOLA municipio     3000 non-null   object
 6   Nombre municipio              3000 non-null   object
 7   Edad                          3000 non-null   int64
 8   Unidad de medida de edad      3000 non-null   int64
 9   Sexo                          3000 non-null   object
 10  Tipo de contagio              3000 non-null   object
 11  Ubicación del caso            3000 non-null   object
 12  Estado                        3000 non-null   object
 13  Recuperado                    3000 non-null   object
 14  Fecha de inicio de síntomas   3000 non-null   object
 15  Fecha de muerte               3000 non-null   object
 16  Fecha de diagnóstico          3000 non-null   object
 17  Fecha de recuperación         2918 non-null   object
 18  Tipo de recuperación          2918 non-null   object
 19  Pertenencia étnica            3000 non-null   float64
 20  Nombre del grupo étnico       3000 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 492.3+ KB

In [24]:
## Limpieza de nulos residuales detectados en el .info()
# Recuperado (Faltaban 20): Rellenar basado en si tiene fecha de muerte o no
df_concat['Recuperado'] = df_concat['Recuperado'].fillna(
    df_concat['Fecha de muerte'].apply(lambda x: 'Fallecido' if x != 'No aplica' else 'Recuperado')
)

# Fecha de diagnóstico (Faltaba 1): Rellenar con la fecha de notificación
df_concat['Fecha de diagnóstico'] = df_concat['Fecha de diagnóstico'].fillna(df_concat['Fecha de notificación'])

# Pertenencia étnica (Faltaba 1): Rellenar con la moda de la columna
df_concat['Pertenencia étnica'] = df_concat['Pertenencia étnica'].fillna(df_concat['Pertenencia étnica'].mode()[0])

###################

# Agregamos un fillna general por si algún vivo quedó sin estos datos
df_concat['Fecha de recuperación'] = df_concat['Fecha de recuperación'].fillna('No aplica')
df_concat['Tipo de recuperación'] = df_concat['Tipo de recuperación'].fillna('No aplica')

# Revisar el estado de la tabla actualmente
df_concat.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3000 entries, 0 to 2999
Data columns (total 21 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   fecha reporte web             3000 non-null   object
 1   ID de caso                    3000 non-null   object
 2   Fecha de notificación         3000 non-null   object
 3   Código DIVIPOLA departamento  3000 non-null   object
 4   Nombre departamento           3000 non-null   object
 5   Código DIVIPOLA municipio     3000 non-null   object
 6   Nombre municipio              3000 non-null   object
 7   Edad                          3000 non-null   int64
 8   Unidad de medida de edad      3000 non-null   int64
 9   Sexo                          3000 non-null   object
 10  Tipo de contagio              3000 non-null   object
 11  Ubicación del caso            3000 non-null   object
 12  Estado                        3000 non-null   object
 13  Recuperado                    3000 non-null   object
 14  Fecha de inicio de síntomas   3000 non-null   object
 15  Fecha de muerte               3000 non-null   object
 16  Fecha de diagnóstico          3000 non-null   object
 17  Fecha de recuperación         3000 non-null   object
 18  Tipo de recuperación          3000 non-null   object
 19  Pertenencia étnica            3000 non-null   float64
 20  Nombre del grupo étnico       3000 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 492.3+ KB

In [55]:
# Verificar los tipos de datos correctos

In [56]:
# Consistencia de categorias

In [57]:
# Outliers

In [58]:
# Rangos lógicos

# 3. Entender los datos

In [59]:
# Matriz de diagrama de dispersión -> saber como se relacionan todas ellas entre si