<a href="https://colab.research.google.com/github/dmhenaopa/EDCO/blob/main/Semana2/Sesion3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Aprender a conectarnos al drive**

Desde colab para escribir y leer archivos del drive

In [16]:
from google.colab import drive
drive.mount('/content/drive', force_remount = True) # Montar el disco para acceso al drive

Mounted at /content/drive

In [17]:
# Librerias
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Sistema operativo
import os

In [18]:
# Directorio actual
!pwd # En python, llamar comando de linux con signos de admiración !

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Transport endpoint is not connected
pwd: error retrieving current directory: getcwd: cannot access parent directories: Transport endpoint is not connected

In [19]:
# Listar el contenido en la carpeta
!ls

shell-init: error retrieving current directory: getcwd: cannot access parent directories: Transport endpoint is not connected
ls: cannot open directory '.': Transport endpoint is not connected

In [20]:
# Movernos de carpeta
ruta = "/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2"
os.chdir(ruta)

In [21]:
!pwd # Comprobar la carpeta

/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2

Necesitamos reservar el espacio para poder escribir dentro archivos y carpetas

In [22]:
# Crear carpeta de salida
salida = "Carpeta_salida"
os.makedirs(salida, exist_ok = True) # True para no reescribir la carpeta en caso de que exista

In [54]:
# Crear 40 carpetas en la carpeta de salida - revisar el lugar en donde esta creandolas, este no es
ruta = "/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2/Carpeta_salida"
!pwd

for i in range(0, 40):
  subcarpeta = 'sub_{}'.format(i)

  print('Creando carpeta:', subcarpeta)
  os.makedirs(subcarpeta, exist_ok = True)

/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2/Carpeta_salida
Creando carpeta: sub_0
Creando carpeta: sub_1
Creando carpeta: sub_2
Creando carpeta: sub_3
Creando carpeta: sub_4
Creando carpeta: sub_5
Creando carpeta: sub_6
Creando carpeta: sub_7
Creando carpeta: sub_8
Creando carpeta: sub_9
Creando carpeta: sub_10
Creando carpeta: sub_11
Creando carpeta: sub_12
Creando carpeta: sub_13
Creando carpeta: sub_14
Creando carpeta: sub_15
Creando carpeta: sub_16
Creando carpeta: sub_17
Creando carpeta: sub_18
Creando carpeta: sub_19
Creando carpeta: sub_20
Creando carpeta: sub_21
Creando carpeta: sub_22
Creando carpeta: sub_23
Creando carpeta: sub_24
Creando carpeta: sub_25
Creando carpeta: sub_26
Creando carpeta: sub_27
Creando carpeta: sub_28
Creando carpeta: sub_29
Creando carpeta: sub_30
Creando carpeta: sub_31
Creando carpeta: sub_32
Creando carpeta: sub_33
Creando carpeta: sub_34
Creando carpeta: sub_35
Creando carpeta: sub_36
Creando carpeta: sub_37
Creando carpeta: sub_38
Creando carpeta: sub_39

Revisar nuestras bases de datos

In [24]:
BaseDatos = {
    1001: { 'Nombre': 'Pepito', 'Apellido': 'Perezito', 'Edad': 35, 'Genero': 'M' },
    1002: { 'Nombre': 'Pepita', 'Apellido': 'Perezita', 'Edad': 25, 'Genero': 'F' },
    1003: { 'Nombre': 'Pepite', 'Apellido': 'Perezite', 'Edad': 28, 'Genero': 'M' },
}

In [28]:
# Primer dataframe
df = pd.DataFrame.from_dict(BaseDatos, orient='index')
df

      Nombre  Apellido  Edad Genero
1001  Pepito  Perezito    35      M
1002  Pepita  Perezita    25      F
1003  Pepite  Perezite    28      M

In [ ]:
# Elegir una columna de los datos
df['Edad']

In [30]:
# Pandas básico
df.index.name = 'ID'
df

      Nombre  Apellido  Edad Genero
ID
1001  Pepito  Perezito    35      M
1002  Pepita  Perezita    25      F
1003  Pepite  Perezite    28      M

In [31]:
# Podemos convertir el ID en una columna
df = df.reset_index()
df

     ID  Nombre  Apellido  Edad Genero
0  1001  Pepito  Perezito    35      M
1  1002  Pepita  Perezita    25      F
2  1003  Pepite  Perezite    28      M

In [33]:
# Visualizar los dataframe
df.head(2)

     ID  Nombre  Apellido  Edad Genero
0  1001  Pepito  Perezito    35      M
1  1002  Pepita  Perezita    25      F

In [32]:
# Dimensión de la matriz o de la tabla de datos
# R1 nombre, R2 apellido, R3 edad, R4 Genero - El id no es explicativo entonces realmente no va
df.shape # Esto da un (3, 5) - 3 entradas, 5 columnas - Dimension de la matriz o tamaño

(3, 5)

In [35]:
# Como consultar el nombre de las columnas
df.keys()

# o
df.columns

# Consultar los tipos
df.dtypes

ID           int64
Nombre      object
Apellido    object
Edad         int64
Genero      object
dtype: object

In [37]:
# Nombre de columnas que tenemos, tipos, el uso de memoria
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ID        3 non-null      int64
 1   Nombre    3 non-null      object
 2   Apellido  3 non-null      object
 3   Edad      3 non-null      int64
 4   Genero    3 non-null      object
dtypes: int64(2), object(3)
memory usage: 252.0+ bytes

In [38]:
# Pequeña estadistica de los datos númericos
df.describe()

           ID       Edad
count     3.0   3.000000
mean   1002.0  29.333333
std       1.0   5.131601
min    1001.0  25.000000
25%    1001.5  26.500000
50%    1002.0  28.000000
75%    1002.5  31.500000
max    1003.0  35.000000

In [42]:
# Queremos escoger solo unas columnas especificas
df1 = df[['Edad', 'Genero']] # Lista con las columnas que quiero
df1

   Edad Genero
0    35      M
1    25      F
2    28      M

In [45]:
# Aplicar mascaras "masking" o filtros
# Personas mayores a 25
mask = df['Edad'] > 25 # Esto es una condición
df2 = df[mask]
df2

     ID  Nombre  Apellido  Edad Genero
0  1001  Pepito  Perezito    35      M
2  1003  Pepite  Perezite    28      M

In [46]:
mask2 = df[ 'Genero' ] == 'M'
mask2

df[mask2]

     ID  Nombre  Apellido  Edad Genero
0  1001  Pepito  Perezito    35      M
2  1003  Pepite  Perezite    28      M

In [ ]:
# Filtro 1 es que tenga más de 25 y el dos que sea del genero másculino
df[mask & mask2] # Y
df[mask | mask2] # O

In [47]:
# Cómo consultar una entrada en particular
df.loc[1] # Ubicación 1

ID              1002
Nombre        Pepita
Apellido    Perezita
Edad              25
Genero             F
Name: 1, dtype: object

In [48]:
# Tomar una porción del dato, estilo álgebra lineal - Slicing - Solo columnas contiguas
# La fila 0, la fila 1... necesitamos las filas y las columnas o features
df.iloc[1,:] # Todos
df.iloc[1,1:4] # Solo el nombre y la edad

df[['Nombre', 'Genero']].iloc[:2,:] # Elijo las columnas que quiero y entonces tomo la opción

   Nombre Genero
0  Pepito      M
1  Pepita      F

In [49]:
# En cada subcarpeta quiero guardar los datos
!pwd
df.to_csv('personal.csv') # Esto solo guarda uno en un lugar especifico

/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2

In [59]:
for i in range (0, 40):
  subcarpeta = 'moviendonos a sub_{}'.format(i)
  os.chdir("/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2/Carpeta_salida")
  os.chdir('sub_{}'.format(i))
  !pwd
  df.to_csv('personal.csv')

/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2/Carpeta_salida/sub_0
/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2/Carpeta_salida/sub_1
/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2/Carpeta_salida/sub_2
/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2/Carpeta_salida/sub_3
/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2/Carpeta_salida/sub_4
/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2/Carpeta_salida/sub_5
/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2/Carpeta_salida/sub_6
/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2/Carpeta_salida/sub_7
/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2/Carpeta_salida/sub_8
/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2/Carpeta_salida/sub_9
/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2/Carpeta_salida/sub_10
/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2/Carpeta_salida/sub_11
/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2/Carpeta_salida/sub_12
/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2/Carpeta_salida/sub_13
/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2/Carpeta_salida/sub_14
/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2/Carpeta_salida/sub_15
/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2/Carpeta_salida/sub_16
/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2/Carpeta_salida/sub_17
/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2/Carpeta_salida/sub_18
/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2/Carpeta_salida/sub_19
/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2/Carpeta_salida/sub_20
/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2/Carpeta_salida/sub_21
/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2/Carpeta_salida/sub_22
/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2/Carpeta_salida/sub_23
/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2/Carpeta_salida/sub_24
/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2/Carpeta_salida/sub_25
/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2/Carpeta_salida/sub_26
/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2/Carpeta_salida/sub_27
/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2/Carpeta_salida/sub_28
/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2/Carpeta_salida/sub_29
/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2/Carpeta_salida/sub_30
/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2/Carpeta_salida/sub_31
/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2/Carpeta_salida/sub_32
/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2/Carpeta_salida/sub_33
/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2/Carpeta_salida/sub_34
/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2/Carpeta_salida/sub_35
/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2/Carpeta_salida/sub_36
/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2/Carpeta_salida/sub_37
/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2/Carpeta_salida/sub_38
/content/drive/MyDrive/EDCO_IntroCienciaDatos/Semana2/Carpeta_salida/sub_39

In [ ]:
# En cada subcarpeta quiero guardar una gráfica